'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const express_1 = require('express');
const router = express_1.Router();
const controller_1 = require('./controller/controller');
router.post('/tracks', controller_1.getTracks);
router.post('/tokens', controller_1.getTokens);
router.post('/artists', controller_1.getArtists);
router.post('/create', controller_1.createPlaylist);
router.post('/cover', controller_1.getPlaylistCover);
exports.default = router;
